import { User } from '../interfaces/user.interface';

export const USERS: User[] = [
  {
    id: '1',
    name: 'Andrew',
    totalTasks: 7,
    remainingTasks: 3,
    description: 'Full-stack developer',
    team: 'Engineering',
    dateStarted: '2023-11-15T14:22:10Z',
  },
  {
    id: '2',
    name: 'Rachel',
    totalTasks: 6,
    remainingTasks: 1,
    description: 'Product manager',
    team: 'Product',
    dateStarted: '2024-07-08T09:45:33Z',
  },
  {
    id: '3',
    name: 'John',
    totalTasks: 4,
    remainingTasks: 2,
    description: 'UI/UX designer',
    team: 'Design',
    dateStarted: '2022-02-27T18:10:05Z',
  },
  {
    id: '4',
    name: 'Jake',
    totalTasks: 9,
    remainingTasks: 4,
    description: 'Software tester',
    team: 'Quality Assurance',
    dateStarted: '2026-03-19T03:55:47Z',
  },
  {
    id: '5',
    name: 'Charlotte',
    totalTasks: 5,
    remainingTasks: 0,
    description: 'Data analyst',
    team: 'Analytics',
    dateStarted: '2025-09-30T23:01:12Z',
  },
  {
    id: '6',
    name: 'Kendall',
    totalTasks: 5,
    remainingTasks: 2,
    description: 'Some employee',
    team: 'Some team',
    dateStarted: '2027-08-30T23:01:12Z',
  },
  {
    id: '7',
    name: 'Jordan',
    totalTasks: 8,
    remainingTasks: 3,
    description: 'Team leader for analytics',
    team: 'Data Science',
    dateStarted: '2023-04-15T10:20:30Z',
  },
  {
    id: '8',
    name: 'Morgan',
    totalTasks: 6,
    remainingTasks: 1,
    description: 'Frontend developer',
    team: 'Web Dev',
    dateStarted: '2022-11-05T08:45:00Z',
  },
  {
    id: '9',
    name: 'Riley',
    totalTasks: 10,
    remainingTasks: 5,
    description: 'QA specialist',
    team: 'Quality Assurance',
    dateStarted: '2024-01-20T15:33:12Z',
  },
  {
    id: '10',
    name: 'Taylor',
    totalTasks: 4,
    remainingTasks: 0,
    description: 'Marketing intern',
    team: 'Marketing',
    dateStarted: '2023-06-10T12:00:00Z',
  },
  {
    id: '11',
    name: 'Avery',
    totalTasks: 7,
    remainingTasks: 4,
    description: 'Mobile app developer',
    team: 'App Dev',
    dateStarted: '2023-09-25T09:10:45Z',
  },
  {
    id: '12',
    name: 'Kendall',
    totalTasks: 5,
    remainingTasks: 2,
    description: 'Some employee',
    team: 'Some team',
    dateStarted: '2027-08-30T23:01:12Z',
  },
  {
    id: '13',
    name: 'Charlie',
    totalTasks: 3,
    remainingTasks: 1,
    description: 'Tech support representative',
    team: 'Support',
    dateStarted: '2021-03-12T07:50:00Z',
  },
  {
    id: '14',
    name: 'Skyler',
    totalTasks: 9,
    remainingTasks: 6,
    description: 'UX researcher',
    team: 'Design',
    dateStarted: '2022-08-18T16:22:30Z',
  },
  {
    id: '15',
    name: 'Peyton',
    totalTasks: 11,
    remainingTasks: 7,
    description: 'Backend engineer',
    team: 'Platform Engineering',
    dateStarted: '2023-12-01T11:15:00Z',
  },
  {
    id: '16',
    name: 'Casey',
    totalTasks: 2,
    remainingTasks: 0,
    description: 'Content writer',
    team: 'Editorial',
    dateStarted: '2022-05-07T14:40:20Z',
  },
  {
    id: '17',
    name: 'Dakota',
    totalTasks: 6,
    remainingTasks: 2,
    description: 'DevOps engineer',
    team: 'Infrastructure',
    dateStarted: '2024-10-03T08:15:30Z',
  },
  {
    id: '18',
    name: 'Emerson',
    totalTasks: 9,
    remainingTasks: 4,
    description: 'Project coordinator',
    team: 'Operations',
    dateStarted: '2023-02-14T13:40:10Z',
  },
  {
    id: '19',
    name: 'Harper',
    totalTasks: 5,
    remainingTasks: 1,
    description: 'Customer success manager',
    team: 'Client Services',
    dateStarted: '2022-07-19T17:25:50Z',
  },
  {
    id: '20',
    name: 'Reese',
    totalTasks: 7,
    remainingTasks: 3,
    description: 'Security analyst',
    team: 'Cybersecurity',
    dateStarted: '2025-03-11T06:55:00Z',
  },
  {
    id: '21',
    name: 'Quinn',
    totalTasks: 4,
    remainingTasks: 0,
    description: 'HR generalist',
    team: 'Human Resources',
    dateStarted: '2021-09-28T11:30:45Z',
  },
];
